<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ChangeSessionIdentifierSecure.aspx.cs" Inherits="SwingsetDotNet.ChangeSessionIdentifierSecure" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--#include virtual="/header.aspx"--> 
 
<h2 align="center">Exercise: Change Session Identifier</h2>

<p>Original Cookie (saved in session)</p>
<table align="center" border="1" width="60%"><tr><td align="center">
	<br>JSESSIONID=<asp:Label ID="Orig" runat="server" /><br><br>
</td></tr></table>

<p>Current Cookie (generated by JavaScript in browser)</p>
<table align="center" border="1" width="60%"><tr><td align="center">
	<br><script>document.write(document.cookie)</script><br><br>
</td></tr></table>
<p>Click <asp:HyperLink ID="ChangeSessionIdentifierInsecure" Text="here" NavigateUrl="~/ChangeSessionIdentifierSecure.aspx?function=ChangeSessionIdentifier&mode=secure" runat="server" /> to refresh the page with a new session identifier.</p>   
<!--#include virtual="/footer.aspx"-->