<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ChangeSessionIdentifierInsecure.aspx.cs" Inherits="SwingsetDotNet.ChangeSessionIdentifierInsecure" ValidateRequest="false" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--#include virtual="/header.aspx"--> 
    
<h2>Exercise: Change Session Identifier</h2>

<p>Current Cookie (generated by JavaScript in browser)</p>
<table align="center" border="1" width="60%"><tr><td align="center">
	<br><script>document.write(document.cookie)</script><br><br>
</td></tr></table>

<p>Click <asp:HyperLink ID="lkChangeInsecure" Text="here" NavigateUrl="~/ChangeSessionIdentifierInsecure.aspx?function=ChangeSessionIdentifier&mode=insecure" runat="server" /> to refresh the page.</p>    

<!--#include virtual="/footer.aspx"-->
